### ISSUE TITLE
1858: TBF can lay token in Zaragoza even though space should be reserved for the Z&P

### ISSUE THREAD

**Issue by ianwilson156** [ollybh/18xx#62] opened 2023-02-14 20:56 UTC
OR3.,2 - I'll send the JSON by email as usual

**Comment by ollybh** [comment] 2023-04-23 17:02
Here's what's going wrong:
-  In SR3 ZPB is formed from M&Z, using the M&Z's reservation ability to place a token in Zaragoza.
-  In OR3.1 ZPB upgrades Zaragoza to green. At this point there are two token slots.
   * Slot 0: ZPB token, M&Z reservation.
   * Slot 1: No token, Z&P reservation.
- At the end of ZPB's dividends step M&Z closes. At this point the slots in Zaragoza look like:
   * Slot 0: ZPB token, Z&P reservation.
   * Slot 1: No token, no reservation.
- Slot 1 is now available for TBF to place a token.

The problem is that `City.reservations` is a simple array, so when there's just one reservation this has to be against slot 0. Do the reservations need to get switched when the private closes? Or is this an upstream bug?

**Comment by ianwilson156** [comment] 2023-04-23 19:34
It looks like the error happens when the private closes. What should happen is:
* Slot A: ZPB token, no reservation
* Slot B: No token, Z&P reservation
How A & B map onto 0 & 1 is up to you, but sounds like B=0 is necessary. In which case, yes, the reservations need to switch in this situation.

**Comment by ollybh** [comment] 2023-04-27 19:57
Fixed in commit 9a764daf7.

**Closed by ollybh** 2023-04-27 19:57 UTC
Labels: 1858
