### ISSUE TITLE
Token step not processing place_token action

### ISSUE THREAD

**Issue by ianwilson156** [ollybh/18xx#34] opened 2022-11-17 17:06 UTC
OR3.2 RP attempts to lay a token in Cordoba (which it cannot afford), I get the following error message:
"Blocking Step run routes cannot process action 284"

This may just be that a more intelligible message is needed e.g "cannot lay token: insufficient funds"

**Comment by ollybh** [comment] 2022-11-19 13:21
No, that's a proper bug. For some reason your place token action isn't getting processed by the token step, and passed on to the run routes step which wants nothing to do with it. This is probably something I messed up when fixing issue #1.

Can you send me the JSON file for this game?

**Comment by ollybh** [comment] 2022-11-20 19:15
Fixed in commit 3e1311a3d. This was caused by a token location being chosen which the company could not afford, but the correct code path for handling this was not selected. The tokening step will now be skipped if there are no affordable token locations available.

**Closed by ollybh** 2022-11-20 19:15 UTC
Labels: bug, 1858

**Comment by ianwilson156** [comment] 2022-11-20 19:42
In that instance, the RP did have an affordable token (in Lisboa) & that worked fine  - it was only the unaffordable one which caused the issue.
