### ISSUE TITLE
1858: Cannot build outside of home hexes until all completed

### ISSUE THREAD

**Issue by ianwilson156** [ollybh/18xx#24] opened 2022-11-08 20:24 UTC
B&CR built F15 and then wanted to build G16, but couldn't until it had built all 3 home hexes. This was ok before!

**Comment by ollybh** [comment] 2022-11-08 22:41
This is a duplicate of issue #7. Privates can build outside their home hexes, if the track connects to a revenue centre (town or city) in their home hexes. If there's just plain track it isn't working.

**Closed** 2022-11-08 22:41 UTC
Labels: 1858
